## Bibliotecas necessárias

library(DBI)
library(dplyr)
library(googlesheets4)

## conexão com banco replica 

con2 <- dbConnect(odbc::odbc(), "reproreplica")


#CURRENT MONTH

pedidosatd <- dbGetQuery(con2,"
  
  WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
  SETOR AS (SELECT ZOCODIGO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,28)),
  
  CLI AS (SELECT C.CLICODIGO,CLINOMEFANT CLIENTE,GCLCODIGO,ZODESCRICAO SETOR,C.FUNCODIGO2,
  FUNNOME NOME FROM CLIEN C
INNER JOIN (SELECT CLICODIGO,E.ZOCODIGO,ZODESCRICAO FROM ENDCLI E
INNER JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA 
WHERE ZOCODIGO IN (20,21,22,23,24,25,28))Z ON E.ZOCODIGO=Z.ZOCODIGO
WHERE ENDFAT='S') ED ON C.CLICODIGO=ED.CLICODIGO
LEFT JOIN FUNCIO F ON C.FUNCODIGO2=F.FUNCODIGO
WHERE CLICLIENTE='S'
),

  
  PED AS (SELECT ID_PEDIDO,CLIENTE,PEDDTEMIS,P.CLICODIGO,GCLCODIGO,SETOR,C.FUNCODIGO2,NOME FROM PEDID P
  INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
   INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO 
    WHERE PEDDTEMIS BETWEEN '01.01.2022' AND 'TODAY' AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))
  
  
  SELECT ID_PEDIDO,CLICODIGO,CLIENTE,FUNCODIGO2 CODFUNC,SETOR,NOME
   FROM PED
  ")  


View(pedidosatd)

pdatd <- pedidosatd %>% 
   group_by(CLICODIGO,CLIENTE,SETOR,NOME,CODFUNC) %>% 
      summarize(QTD_PEDIDOS=n_distinct(ID_PEDIDO)) %>% arrange(desc(QTD_PEDIDOS))

View(pdatd)

sheet_write(pdatd,ss="1W1aqBSpHOWMfo8iUwv-V33J1oiB77hc-a6eZOU-KQ3w",sheet="DADOS")
