

WITH PED AS (SELECT ID_PEDIDO,CLICODIGO,PEDDTEMIS,FUNCODIGO2 FROM PEDID
WHERE PEDDTEMIS BETWEEN 
DATEADD(-60 DAY TO CURRENT_DATE) AND 'TODAY' ),

USU AS (SELECT USUCODIGO,USUNOME FROM USUARIO)


SELECT EMPCODIGO EMPRESA,
         CLICODIGO,
          LPCODIGO APONTAMENTO,
           A.ID_PEDIDO,
             USUNOME USUARIO,
              FUNNOME NOME,
               CAST (APOBS AS VARCHAR (100) )OBS,
                APDATA FROM ACOPED A
INNER JOIN PED P ON A.ID_PEDIDO=P.ID_PEDIDO
LEFT JOIN USU U ON A.USUCODIGO=U.USUCODIGO
LEFT JOIN (SELECT FUNNOME,FUNCODIGO FROM FUNCIO) B ON A.USUCODIGO=B.FUNCODIGO 
WHERE LPCODIGO=2026